name: Test (Release Please)

on:
  push:
    branches:
      - release-please--branches--*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip tests for release-please PR (only updates CHANGELOG and version)"
